import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, Clock3, MapPin, MessageCircle, Phone } from "lucide-react";

const phone = "+923338390207";
const whatsappUrl = `https://wa.me/${phone}`;

export const Route = createFileRoute("/appointment")({
  component: AppointmentPage,
  head: () => ({ meta: [{ title: "Book an Appointment | Women Care Clinic Peshawar" }, { name: "description", content: "Book a consultation with Women Care Clinic in Health Net Hospital, Phase 5 Hayatabad, Peshawar." }] }),
});

function AppointmentPage() {
  return <main className="min-h-screen bg-[#fbfaf7] text-slate-950"><section className="mx-auto max-w-5xl px-5 pb-16 pt-32 sm:px-8"><Link to="/" className="text-sm font-semibold text-[#056170]">← Back to clinic</Link><div className="mt-10 text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-rose-600">Appointments</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Book your consultation</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600">Choose the easiest way to contact Women Care Clinic and request an appointment.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2"><a href={whatsappUrl} target="_blank" rel="noreferrer" className="rounded-[2rem] bg-[#056170] p-7 text-white shadow-lg transition hover:-translate-y-1"><MessageCircle className="h-7 w-7"/><h2 className="mt-5 text-2xl font-semibold">Book on WhatsApp</h2><p className="mt-2 text-sm leading-6 text-white/80">Send your preferred date, time and main concern directly to the clinic.</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold">Open WhatsApp <ArrowRight className="h-4 w-4"/></span></a><a href={`tel:${phone}`} className="rounded-[2rem] bg-white p-7 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1"><Phone className="h-7 w-7 text-[#056170]"/><h2 className="mt-5 text-2xl font-semibold">Call the clinic</h2><p className="mt-2 text-sm leading-6 text-slate-600">Speak with the clinic directly to check availability and appointment timing.</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#056170]">+92 333 8390207 <ArrowRight className="h-4 w-4"/></span></a></div><div className="mt-8 rounded-[2rem] border border-slate-200 bg-white p-7"><h2 className="text-xl font-semibold">Clinic details</h2><div className="mt-5 grid gap-5 sm:grid-cols-3"><div className="flex gap-3"><MapPin className="h-5 w-5 shrink-0 text-[#056170]"/><div><p className="text-sm font-semibold">Location</p><p className="mt-1 text-sm leading-6 text-slate-600">Health Net Hospital, Phase 5 Hayatabad, Peshawar</p></div></div><div className="flex gap-3"><Clock3 className="h-5 w-5 shrink-0 text-[#056170]"/><div><p className="text-sm font-semibold">Timings</p><p className="mt-1 text-sm leading-6 text-slate-600">Monday–Saturday<br/>5:00 PM–9:00 PM</p></div></div><div className="flex gap-3"><CalendarDays className="h-5 w-5 shrink-0 text-[#056170]"/><div><p className="text-sm font-semibold">Care areas</p><p className="mt-1 text-sm leading-6 text-slate-600">Gynaecology, pregnancy, fertility & women's health</p></div></div></div></div></section></main>;
}
