import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Award, HeartPulse, ShieldCheck } from "lucide-react";
import doctorPortrait from "@/assets/doctor-portrait.png.asset.json";

export const Route = createFileRoute("/doctor")({
  component: DoctorPage,
  head: () => ({ meta: [{ title: "Asst. Prof. Dr. Laila Nazir | Consultant Gynaecologist Peshawar" }, { name: "description", content: "Meet Asst. Prof. Dr. Laila Nazir, Consultant Gynaecologist & Obstetrician at Women Care Clinic in Peshawar." }] }),
});

function DoctorPage() {
  return <main className="min-h-screen bg-[#fbfaf7] text-slate-950"><section className="mx-auto max-w-6xl px-5 pb-16 pt-32 sm:px-8"><Link to="/" className="text-sm font-semibold text-[#056170]">← Back to clinic</Link><div className="mt-10 grid items-center gap-12 lg:grid-cols-2"><div className="overflow-hidden rounded-[2rem] bg-white shadow-xl ring-1 ring-slate-200"><img src={doctorPortrait.url} alt="Asst. Prof. Dr. Laila Nazir" className="aspect-[4/5] w-full object-cover"/></div><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-rose-600">Meet the doctor</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Asst. Prof. Dr. Laila Nazir</h1><p className="mt-3 text-lg font-medium text-[#056170]">Consultant Gynaecologist & Obstetrician</p><p className="mt-5 text-lg leading-8 text-slate-600">Focused on respectful, evidence-informed and personalized women's healthcare across gynaecology, pregnancy, fertility and preventive care.</p><div className="mt-7 rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 className="text-lg font-semibold">Qualifications</h2><p className="mt-3 text-sm leading-7 text-slate-600">MBBS<br/>FCPS (Obstetrics & Gynecology)<br/>CHPE<br/>MRCPI (II) – Ireland<br/>Member, American College of Obstetricians and Gynecologists (ACOG)</p></div><Link to="/appointment" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#056170] px-6 py-3 text-sm font-semibold text-white">Book with Dr. Laila <ArrowRight className="h-4 w-4"/></Link></div></div></section><section className="bg-white"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><div className="grid gap-5 md:grid-cols-3">{[[Award,"Clinical experience","12+ years of clinical experience in women’s health."],[HeartPulse,"Personalized care","Consultations centered on your symptoms, goals and needs."],[ShieldCheck,"Privacy focused","A respectful environment for sensitive conversations."]].map(([I,t,d])=>{const Icon=I as typeof Award;return <div key={String(t)} className="rounded-3xl bg-[#fbfaf7] p-6"><Icon className="h-6 w-6 text-[#056170]"/><h2 className="mt-4 text-lg font-semibold">{t}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></div>})}</div></div></section></main>;
}
