import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Baby, CheckCircle2, HeartPulse, ShieldCheck } from "lucide-react";
import maternityImage from "@/assets/maternity-newborn.png.asset.json";

export const Route = createFileRoute("/maternity")({
  component: MaternityPage,
  head: () => ({ meta: [{ title: "Maternity & Pregnancy Care in Peshawar | Women Care Clinic" }, { name: "description", content: "Pregnancy, delivery planning and postnatal maternity care at Women Care Clinic in Hayatabad, Peshawar." }] }),
});

function MaternityPage() {
  return <main className="min-h-screen bg-[#fbfaf7] text-slate-950"><section className="mx-auto max-w-7xl px-5 pb-16 pt-32 sm:px-8"><Link to="/" className="text-sm font-semibold text-[#056170]">← Back to clinic</Link><div className="mt-9 grid items-center gap-10 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-rose-600">Maternity care</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Pregnancy care with clear guidance at every stage.</h1><p className="mt-5 text-lg leading-8 text-slate-600">Get structured support through antenatal visits, birth planning, delivery care and recovery with a women-focused approach.</p><Link to="/appointment" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#056170] px-6 py-3 text-sm font-semibold text-white">Book maternity consultation <ArrowRight className="h-4 w-4" /></Link></div><img src={maternityImage.url} alt="Mother and newborn maternity care" className="w-full rounded-[2rem] object-cover shadow-xl" /></div></section><section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="grid gap-5 md:grid-cols-3">{[[Baby,"Antenatal Care","Regular pregnancy guidance and monitoring."],[ShieldCheck,"Birth Planning","Understand your delivery options and prepare with confidence."],[HeartPulse,"Postnatal Support","Support after delivery as you recover and adjust." ]].map(([I,t,d])=>{const Icon=I as typeof Baby;return <div key={String(t)} className="rounded-3xl border border-slate-200 p-6"><Icon className="h-7 w-7 text-[#056170]"/><h2 className="mt-4 text-lg font-semibold">{t}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></div>})}</div><div className="mt-10 rounded-[2rem] bg-[#f2f8f7] p-7"><h2 className="text-2xl font-semibold">What maternity care can include</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{["Antenatal Care","Normal Delivery","C-Section","Postnatal Care","Pregnancy concerns","Delivery planning"].map(x=><div key={x} className="flex items-center gap-2 text-sm text-slate-700"><CheckCircle2 className="h-4 w-4 text-[#056170]"/> {x}</div>)}</div></div></div></section></main>;
}
